const ZU_TEXT = {
  "Home": "Ekhaya", "Brain Lab": "Ilabhorethri Yobuchopho", "Observer": "Ukubuka", "Journey": "Uhambo", "Welcome": "Siyakwamukela", "Try a Strategy": "Zama Isu", "Reflect & Learn": "Cabanga Futhi Ufunde", "Gratitude": "Ukubonga", "Self Check-In": "Ukuzihlola", "Save": "Londoloza", "← Back": "← Emuva", "My Evidence Journey": "Uhambo Lwami Lobufakazi",
  "My Self-Learning Journey": "Uhambo Lwami Lokuzifundela", "Notice · Try · Reflect · Grow": "Qaphela · Zama · Cabanga · Khula", "Learn a brain principle, step back into Observer View, test a strategy, gather evidence, and choose your next step.": "Funda ngomqondo wobuchopho, zibuke ngokucophelela, uhlole isu, uqoqe ubufakazi, bese ukhetha isinyathelo esilandelayo.",
  "Understand Myself": "Ngiziqonde Njengomfundi", "Explore how your interests, attention, feelings, and environment affect learning.": "Hlola ukuthi izinto ozithandayo, ukunaka, imizwa nendawo ekuzungezile kuthinta kanjani ukufunda kwakho.", "Learn practical brain principles.": "Funda ngemigomo yobuchopho ongayisebenzisa empilweni.", "Observer View": "Ukuzibuka Ngokucophelela", "Describe the scene with curiosity.": "Chaza okwenzekayo ngokufuna ukwazi.", "Test one helpful idea.": "Hlola umqondo owodwa ongakusiza.", "Reflect on My Learning": "Ngicabange Ngokufunda Kwami", "Look back at what you noticed, what helped, and what you will try next.": "Bheka lokho okuqaphele, okukusizile nokuzozama ngokulandelayo.", "Notice something good without ignoring what is difficult.": "Qaphela okuhle ngaphandle kokuziba ubunzima.", "Review patterns and insights.": "Bheka amaphethini nemibono oyitholile.",
  "Reliable information gives you possibilities, not labels. Choose a category, learn one idea in simple words, then observe yourself and try it.": "Ulwazi oluthembekile lukunikeza izindlela ongazicabangela, hhayi amalebula. Khetha isigaba, ufunde umqondo ngamagama alula, bese uzibuka futhi uwuzame.", "What this means": "Lokhu kusho ukuthini", "Example:": "Isibonelo:", "Find your evidence": "Thola ubufakazi bakho", "Try it out": "Kuzame", "Try this in an experiment": "Kuzame ekuhloleni isu",
  "Create My Learner Profile": "Dala Iphrofayela Yami Yokufunda", "Use a name you are comfortable using in this app. Your name stays on this device and is not sent to the shared evidence database.": "Sebenzisa igama okhululekile ukulisebenzisa kulolu hlelo lokusebenza. Igama lakho lihlala kule divayisi futhi alithunyelwa kusizindalwazi sobufakazi.", "What should we call you?": "Sikubize ngokuthini?", "How old are you? (10-15)": "Uneminyaka emingaki? (10–15)", "Continue to Understand Myself": "Qhubeka ukuze ngiziqonde",
  "You are not being diagnosed or judged. You are collecting clues about your own learning so you can investigate what helps.": "Akukho muntu okuxilongayo noma okwahlulelayo. Uqoqa izinkomba ngokufunda kwakho ukuze uhlole okukusizayo.", "What matters to you, and what are you curious about?": "Yini ebalulekile kuwe, futhi yini ofisa ukuyazi?", "What do you think you may already do well?": "Yini ocabanga ukuthi usuyenza kahle?", "What can feel difficult when you learn?": "Yini engaba nzima kuwe lapho ufunda?", "When do you focus well, and what usually distracts you?": "Kunini lapho ugxila kahle khona, futhi yini evame ukukuphazamisa?", "How can your feelings or energy affect your learning?": "Imizwa noma amandla akho kungakuthinta kanjani ukufunda?", "What place, people, tools, or routines help you learn?": "Iyiphi indawo, abantu, amathuluzi noma imikhuba ekusiza ufunde?", "What do you want to understand better about yourself?": "Yini ofisa ukuyiqonda kangcono ngawe?", "Save my starting observations": "Londoloza engikuqaphele ekuqaleni",
  "Be a kind scientist, not a judge. Describe what happened before deciding what it means.": "Yiba umcwaningi onomusa, hhayi umahluleli. Chaza okwenzekile ngaphambi kokunquma ukuthi kusho ukuthini.", "What would a kind camera have seen you doing?": "Ikhamera enomusa ibizokubona wenzani?", "What thoughts, feelings, or body signals did you notice?": "Yimiphi imicabango, imizwa noma izimpawu zomzimba oziqaphelile?", "What was happening around you?": "Bekwenzekani eduze kwakho?", "What might this learner need or try next?": "Lo mfundi angadinga ini noma azame ini ngokulandelayo?",
  "Try one task in your usual way, then try it again with a different strategy. Compare what happened.": "Zama umsebenzi ngendlela ojwayele ukuyenza ngayo, bese uzama futhi usebenzisa isu elihlukile. Qhathanisa okwenzekile.", "You chose to investigate:": "Ukhethe ukuphenya lokhu:", "Collect evidence by changing one small thing, observing what happens, and comparing it with your usual approach.": "Qoqa ubufakazi ngokushintsha into eyodwa encane, uqaphele okwenzekayo, bese ukuqhathanisa nendlela ojwayele ukwenza ngayo.", "What small learning task will you try?": "Yimuphi umsebenzi omncane wokufunda ozowuzama?", "How do you normally approach this task?": "Uvame ukuwenza kanjani lo msebenzi?", "Choose a different strategy to test": "Khetha isu elihlukile ozolihlola", "Explain it in your own words": "Chaza ngamagama akho", "Recall it without looking": "Khumbula ngaphandle kokubheka", "Draw a concept map": "Dweba imephu yomqondo", "Break it into smaller parts": "Hlukanisa ube izingxenye ezincane", "Ask for help": "Cela usizo", "What do you predict will happen with the different strategy?": "Ucabanga ukuthi kuzokwenzekani uma usebenzisa isu elihlukile?", "What happened with your usual strategy?": "Kwenzekeni ngesikhathi usebenzisa isu lakho elijwayelekile?", "What happened with the different strategy?": "Kwenzekeni ngesikhathi usebenzisa isu elihlukile?", "Which approach helped more?": "Iyiphi indlela ekusize kakhulu?", "My usual strategy": "Isu lami elijwayelekile", "The different strategy": "Isu elihlukile", "Both about the same": "Womabili acishe afane", "I am not sure yet": "Angikaqiniseki okwamanje", "What will you try next time?": "Yini ozoyizama ngokuzayo?",
  "Reflect on My Learning": "Ngicabange Ngokufunda Kwami", "Reflection is your chance to look back at your evidence, understand what happened, and choose your next step. There are no perfect answers.": "Ukuzindla kuyithuba lakho lokubheka ubufakazi bakho, uqonde okwenzekile, bese ukhetha isinyathelo esilandelayo. Azikho izimpendulo eziphelele.", "What did you notice about yourself as a learner?": "Yini oziqaphele ngayo njengomfundi?", "What helped you learn, remember, concentrate, or continue?": "Yini ekusize wafunda, wakhumbula, wagxila noma waqhubeka?", "What was difficult, confusing, or unhelpful?": "Yini ebikunzima, ikudida noma ingakusizanga?", "What feelings or body signals did you notice while learning?": "Yimiphi imizwa noma izimpawu zomzimba oziqaphele ngenkathi ufunda?", "What in your environment helped or made learning harder?": "Yini endaweni ekuzungezile ekusize noma eyenze ukufunda kwaba nzima?", "What did you learn about yourself or the strategy you tried?": "Yini oyifundile ngawe noma ngesu olizamile?", "What will you try, change, or ask for next time?": "Yini ozoyizama, uyishintshe noma ucele usizo ngayo ngokuzayo?", "Save my reflection": "Londoloza ukuzindla kwami",
  "What is one person, moment, skill, or thing you appreciate today?": "Yimuphi umuntu, umzuzu, ikhono noma into oyibongayo namuhla?", "You are the investigator of your own learning. These are your observations, your scores, and your conclusions.": "Ungumphenyi wokufunda kwakho. Lawa ngamaphuzu akho, izinto oziqaphele neziphetho zakho.", "Observations": "Izinto oziqaphelile", "Experiments compared": "Ukuhlola okuqhathanisiwe", "Reflections": "Ukuzindla", "Gratitude entries": "Amanothi okubonga", "Before and after": "Ngaphambi nangemva", "My comparison": "Ukuqhathanisa kwami", "Understanding": "Ukuqonda", "Self-observation": "Ukuzibuka", "Strategy experimentation": "Ukuhlola isu", "Reflection": "Ukuzindla", "Total": "Isamba", "Confidence": "Ukuzethemba", "Before score": "Amaphuzu angaphambi", "After score": "Amaphuzu angemva", "Not completed": "Akuqediwe", "Your change:": "Ushintsho lwakho:", "confidence points.": "amaphuzu okuzethemba.", "Complete the before self-check before using the activities, then complete the after self-check when finished.": "Qedela ukuzihlola kokuqala ngaphambi kwemisebenzi, bese uqedela ukuzihlola kwangemva uma usuqedile.", "Recent evidence": "Ubufakazi bamuva", "No entries yet.": "Awukafaki lutho.", "Download my evidence report": "Landa umbiko wami wobufakazi", "My starting self-check": "Ukuzihlola kwami kokuqala", "My after self-check": "Ukuzihlola kwami kwangemva", "I can explain one thing about how I learn.": "Ngingachaza into eyodwa ngendlela engifunda ngayo.", "I can notice what helps or distracts me.": "Ngingaqaphela okukusizayo noma okungiphazamisayo.", "I can choose and try a learning strategy.": "Ngingakhetha futhi ngizame isu lokufunda.", "I can explain what happened and decide what to try next.": "Ngingachaza okwenzekile bese nginquma engizokuzama ngokulandelayo.", "Choose 0 if you cannot show this yet, 1 if you can partly show it, or 2 if you can clearly show it. This is your own observation, not a diagnosis.": "Khetha u-0 uma ungakakwazi ukukubonisa, u-1 uma ungakubonisa kancane, noma u-2 uma ungakubonisa ngokucacile. Lokhu ukuzibuka kwakho, akukhona ukuxilongwa.", "0 - Not yet": "0 - Hhayi okwamanje", "1 - Partly": "1 - Kancane", "2 - Clearly": "2 - Ngokucacile", "How confident are you that you understand how you learn? (1–5)": "Uqiniseke kangakanani ukuthi uyayiqonda indlela ofunda ngayo? (1–5)", "Save my starting self-check": "Londoloza ukuzihlola kwami kokuqala", "Save my after self-check": "Londoloza ukuzihlola kwami kwangemva",
  "Back": "Emuva", "Main navigation": "Ukuzulazula okuyinhloko", "Before": "Ngaphambi", "After": "Ngemva", "Recent evidence": "Ubufakazi bamuva", "Download my evidence report": "Landa umbiko wami wobufakazi", "The app will keep your name on this device.": "Uhlelo lokusebenza luzogcina igama lakho kule divayisi.", "Switch to isiZulu": "Shintshela esiZulwini", "Switch to English": "Shintshela esiNgisini",
  "Create my learner profile": "Dala iphrofayela yami yokufunda", "Understand myself": "Ngiziqonde", "Begin my self-check": "Qala ukuzihlola kwami", "Complete my learning experiment": "Qedela ukuhlola kwami isu lokufunda", "Complete my reflection": "Qedela ukuzindla kwami", "Complete my after self-check": "Qedela ukuzihlola kwami kwangemva", "Review my evidence": "Bheka ubufakazi bami", "Scene": "Okwenzekile", "Signals": "Izimpawu", "Context": "Isimo", "Next": "Okulandelayo", "Usual": "Okujwayelekile", "Different strategy": "Isu elihlukile", "Helped more": "Okusize kakhulu", "Insight": "Engikuqondile", "Result": "Umphumela", "Challenge": "Inselele", "Strategy": "Isu", "Reflection": "Ukuzindla", "Experiments": "Ukuhlola", "Confidence": "Ukuzethemba", "Before-use confidence:": "Ukuzethemba ngaphambi kokusebenzisa:", "After-use confidence:": "Ukuzethemba ngemva kokusebenzisa:", "Change:": "Ushintsho:", "Points": "Amaphuzu", "Points / 8": "Amaphuzu / 8", "My check-in results": "Imiphumela yokuzihlola kwami", "Not completed": "Akuqediwe", "context": "Isimo engifunda kuso"
  "Reliable information gives you possibilities, not labels. Choose a category, learn one idea in simple words, then observe yourself and try it.": "Ulwazi oluthembekile lukunikeza izindlela ongazicabangela, hhayi amalebula. Khetha isigaba, ufunde umqondo ngamagama alula, bese uzibuka futhi uwuzame.",
  "Use a name you are comfortable using in this app. Your name stays on this device and is not sent to the shared evidence database.": "Sebenzisa igama okhululekile ukulisebenzisa kulolu hlelo lokusebenza. Igama lakho lihlala kule divayisi futhi alithunyelwa kusizindalwazi sobufakazi.",
  "You chose to investigate:": "Ukhethe ukuphenya lokhu:", "Collect evidence by changing one small thing, observing what happens, and comparing it with your usual approach.": "Qoqa ubufakazi ngokushintsha into eyodwa encane, uqaphele okwenzekayo, bese ukuqhathanisa nendlela ojwayele ukwenza ngayo.",
  "Reflection is your chance to look back at your evidence, understand what happened, and choose your next step. There are no perfect answers.": "Ukuzindla kuyithuba lakho lokubheka ubufakazi bakho, uqonde okwenzekile, bese ukhetha isinyathelo esilandelayo. Azikho izimpendulo eziphelele.", "Save my reflection": "Londoloza ukuzindla kwami",
  "Choose 0 if you cannot show this yet, 1 if you can partly show it, or 2 if you can clearly show it. This is your own observation, not a diagnosis.": "Khetha u-0 uma ungakakwazi ukukubonisa, u-1 uma ungakubonisa kancane, noma u-2 uma ungakubonisa ngokucacile. Lokhu ukuzibuka kwakho, akukhona ukuxilongwa.",
  "Complete the before self-check before using the activities, then complete the after self-check when finished.": "Qedela ukuzihlola kokuqala ngaphambi kwemisebenzi, bese uqedela ukuzihlola kwangemva uma usuqedile.", "My comparison": "Ukuqhathanisa kwami", "Your change:": "Ushintsho lwakho:", "Total": "Isamba", "Not completed": "Akuqediwe", "Review patterns and insights.": "Bheka amaphethini nemibono oyitholile.", "Save my starting observations": "Londoloza engikuqaphele ekuqaleni", "Try this in an experiment": "Kuzame ekuhloleni isu", "confidence points": "amaphuzu okuzethemba", " points and ": " amaphuzu kanye ", " points": " amaphuzu", "Change:": "Ushintsho:", "This record shows learning behaviours, not intelligence or a diagnosis.": "Leli rekhodi libonisa indlela yokufunda, hhayi ukuhlakanipha noma ukuxilongwa.", "Anonymous participant code:": "Ikhodi yomhlanganyeli engadaluli igama:", "Use this summary to support the learner, not judge them.": "Sebenzisa lesi sifinyezo ukweseka umfundi, hhayi ukumahlulela.", "Complete both tests to see a comparison.": "Qedela kokubili ukuzihlola ukuze ubone ukuqhathanisa.", "Your confidence": "Ukuzethemba kwakho"
};

const ZU_CATEGORIES = [
  ["Ziqonde kuqala", "Qala ngemibuzo yakho, izinto ozithandayo, amandla akho nezimo zakho zokufunda."],
  ["Ukuzazi", "Qaphela okwenzekayo ngaphambi kokunquma ukuthi kusho ukuthini."],
  ["Ubuchopho nokushintsha kwabo ngokufunda", "Funda ukuthi amava, ukuzijwayeza, ukunaka nokuphumula kungakuthinta kanjani ukufunda."],
  ["Ukuqaphela nokucabanga njengomcwaningi", "Sebenzisa imibuzo nobufakazi esikhundleni sokuqagela ukuthi ungubani."],
  ["Ukuqonda umehluko ekufundeni", "Abantu bangezwa ukunaka, izinzwa, imizwa, ukunyakaza nokufunda ngezindlela ezahlukene."],
  ["Ukuqaphela umzuzu wamanje", "Naka okwenzekayo manje futhi uqaphele amava akho ngomusa."],
  ["Ukuqonda imizwa", "Imizwa ingakunikeza izinkomba, kodwa ayichazi unomphela lokho ongakwenza."],
  ["Ukubonga", "Qaphela okuhle ngaphandle kokuzenza sengathi ubunzima abukho."],
  ["Ukuhlola nokukhula", "Zama ushintsho olulodwa, uqaphele okwenzekayo, uzindle, bese ulungisa."],
  ["Indlela yokucabanga ngokukhula", "Ukuthuthuka kwakhiwa ngokuzijwayeza, amasu awusizo, impendulo nesikhathi."],
  ["Indawo nezimo zokuphila", "Ukufunda kuthintwa yizimo ezikuzungezile, hhayi okungaphakathi kuwe kuphela."]
];

const ZU_PRINCIPLES = [
 ["Ngingubani?", "Yiziphi izinto ezibalulekile kimi?", "Yini engijabulisayo ukuyenza?", "Yiziphi izinto ezingivusa ilukuluku?", "Yiziphi izinto engizithandayo ngokwemvelo?", "Yiziphi izinto engicabanga ukuthi ngizenza kahle?", "Yiziphi izinto engizithola zinzima?", "Yini engenza ngizethembe?", "Yini engenza ngingazethembi?", "Yini engifisa ukuyiqonda kangcono ngami?", "Ngifunda nini kangcono?", "Ngifunda kuphi kangcono?", "Ngigxila kangcono yini kuthule noma kunomsindo ongemuva?", "Izithombe, amagama, imisindo, ukuboniswa noma ukwenza kungisiza yini ngiqonde?", "Ngikuqonda kangcono yini uma ngichazelwa noma ngizitholela ngokwami?", "Ngingagxila isikhathi esingakanani ngaphambi kokudinga ikhefu?", "Yini evame ukungiphazamisa?", "Yini engisiza ngibuyele emsebenzini uma ngilahlekelwa ukugxila?", "Kwenzekani uma ngingaqondi okuthile?", "Ngivame ukwenzani lapho ukufunda kuba nzima?", "Isimo sami sengqondo sikuthinta kanjani ukufunda?", "Kwenzekani ekufundeni kwami uma ngikhathele?", "Kwenzekani uma ngilambile?", "Kwenzekani uma ngikhathazekile noma ngicindezelekile?", "Yiziphi izindawo ezingenza ngizizwe ngiphephile ngokwanele ukuba ngifunde?", "Yimiphi imisindo, izibani, ukunyakaza noma izinto eziseduze ezithinta ukugxila kwami?", "Ngingacela kubani usizo uma nginenkinga?", "Yimiphi imisebenzi engaphandle kwesikole ethinta isikhathi noma amandla ami?", "Yiziphi izinsiza enginazo?", "Yiziphi izinto endaweni yami ezenza ukufunda kube lula noma kube nzima?"],
 ["Qaphela ngaphambi kokwahlulela", "Hlukanisa amaqiniso nokuqagela", "Yazi lokho ongakwazi", "Ukuzibuka", "Ukuqaphela amaphethini", "Abantu bahlukene", "Amandla nobunzima kungaba khona ndawonye", "Izimo ezikuzungezile zibalulekile", "Cela usizo", "Zikhulumele ngezidingo zakho"],
 ["Ubuchopho buyashintsha ngenxa yamava.", "Ukuzijwayeza kungaqinisa amakhono.", "Ukuphinda kuyasiza.", "Amaphutha anganikeza ulwazi lokufunda.", "Ubunzima abusho ngokuzenzakalela ukuthi awukwazi.", "Amava amasha angaletha ukufunda okusha.", "Ulwazi osunalo luthinta ukufunda okusha.", "Ukunaka kuthinta lokho esikufundayo.", "Ukuphumula kuyingxenye yokufunda.", "Ubuchopho obahlukene bungaba namandla ahlukene.", "Ukufunda kuthatha isikhathi.", "Ukuthuthuka kungaba kancane kancane.", "Ukuqhubeka nokuzijwayeza kubalulekile kunokuzama kanye.", "Amasu asebenzela umuntu oyedwa angase angamsebenzeli omunye ngendlela efanayo.", "Ungazama amasu okufunda ahlukene."],
 ["Ungacabangi ukuthi amava akho afana nawabo bonke abantu.", "Qaphela ngaphambi kokufinyelela esiphethweni.", "Buza ngemava angajwayelekile.", "Sebenzisa imithombo yolwazi ethembekile.", "Qhathanisa ulwazi nalokho okuqaphelile.", "Yenza isibikezelo.", "Hlola isibikezelo.", "Bhala okwenzekayo.", "Bheka amaphethini emiphumeleni yakho.", "Zimisele ukushintsha isiphetho uma kuvela ubufakazi obusha.", "Isehlakalo esisodwa asihlali sifakazela isiphetho.", "Ukuqaphela okuphindaphindiwe kunganikeza ubufakazi obuqinile.", "Kungaba nezincazelo ezahlukene zento efanayo.", "Buza: Yini enye engachaza lokhu?", "Yazi umehluko phakathi kokuqaphela nokuchaza ukuthi kusho ukuthini."],
 ["Abantu bangaba nezindlela ezahlukene zokunaka.", "I-ADHD yisimo sokukhula kobuchopho esingathinta ukunaka, ukulawula izenzo nokuhlela.", "I-autism ingathinta ukuxhumana nabantu, ukuziphatha nokuzwa izinzwa.", "Abanye abantu bezwa ulwazi lwezinzwa ngezindlela ezahlukene.", "Umehluko wokubona ungathinta ukufunda.", "Ubunzima bokuhlanganisa ukunyakaza bungathinta ukubhala nemisebenzi yomzimba.", "Ukukhathazeka kungathinta ukugxila nokufunda.", "I-dyscalculia ingathinta ukuqonda nokusebenzisa izinombolo.", "Ubunzima bokufunda abuchazi ukuhlakanipha noma ukubaluleka komuntu.", "Inselele ingaba khona kanye namandla."],
 ["Naka umzuzu wamanje.", "Qaphela imicabango yakho ngaphandle kokuyikholwa ngokushesha.", "Qaphela imizwa yakho.", "Qaphela okwenzekayo emzimbeni wakho.", "Sebenzisa ukuphefumula ukuze ume isikhashana.", "Qaphela iziphazamiso bese ubuyisela ukunaka ngobumnene.", "Funda ukuqaphela uma usukhungatheka.", "Yima kancane ngaphambi kokuphendula.", "Sebenzisa ukuqaphela ukuze ukhethe ngamabomu.", "Ungakwazi ukuqaphela amava akho."],
 ["Imizwa inikeza ulwazi.", "Imizwa namaqiniso akufani njalo.", "Ukukhungatheka akusho ukuthi awukwazi ukufunda.", "Ukwesaba akusho ukuthi into ayinakwenzeka.", "Qaphela izinto ezivusa imizwa.", "Funda izindlela ezahlukene zokulawula imizwa.", "Zinike isikhathi uma ukhungathekile.", "Khuluma nomuntu uma udinga ukwesekwa.", "Ziphathe ngomusa.", "Isimo sakho semizwa samanje asikuchazi unomphela."],
 ["Qaphela okuhamba kahle.", "Qaphela abantu abakusizayo.", "Bonga amathuba okufunda.", "Qaphela izikhathi ezincane ezinhle.", "Bonisa ukubonga.", "Ukubonga akusho ukuziba izinkinga."],
 ["Zama, qaphela, zindla, bese ulungisa.", "Shintsha isu elilodwa bese uqaphela okwenzekayo.", "Qhathanisa izindlela ezahlukene.", "Gcina umbhalo wokufunda.", "Buza ukuthi yini esebenzile.", "Buza ukuthi yini engasebenzanga.", "Buza ukuthi kungani okuthile kungenzeka kusebenzile.", "Zama futhi usebenzisa isu elihlukile.", "Kala ukuthuthuka ngokuhamba kwesikhathi.", "Sebenzisa ukungaphumeleli njengolwazi.", "Hlala ufuna ukwazi.", "Ungabambeleli endleleni eyodwa kuphela."],
 ["'Angikakakwazi' akufani nokuthi 'angikwazi'.", "Umzamo ungasiza ekuthuthukeni.", "Amasu abalulekile, hhayi umzamo kuphela.", "Impendulo ingasiza ukuthuthuka.", "Izinselele zingakunika amathuba okufunda.", "Ukuthuthuka kubaluleke kakhulu kunokuphelela.", "Ziqhathanise nawe wangaphambili, hhayi nabanye kuphela."],
 ["Indawo okuyo ingathinta ukufunda kwakho.", "Abantu abatholi izinsiza ezilinganayo.", "Ukudla, ukulala, ukuphepha nezindlu kungathinta ukufunda.", "Izinsiza zezikole zingahluka emiphakathini.", "Imisebenzi yomndeni ingathinta isikhathi sokufunda.", "Ulimi namasiko kungathinta amava okufunda.", "Ukucela ukwesekwa kungasiza ukunqoba izithiyo zendawo.", "Izimo zakho ziyingxenye yendaba yakho, kodwa azidingi ukunquma konke ongaba yikho."]
];

function tr(text) { return data.language === "zu" ? (ZU_TEXT[text] || text) : text; }
function localizedCategory(categoryIndex) { const category = PRINCIPLE_CATEGORIES[categoryIndex]; return data.language === "zu" ? { name: ZU_CATEGORIES[categoryIndex][0], description: ZU_CATEGORIES[categoryIndex][1], principles: ZU_PRINCIPLES[categoryIndex] } : category; }
